const $ = s => document.querySelector(s);
const stage=$('#productStage'), bottle=$('#bottle'), cart=$('#cart'), scrim=$('#scrim'), cartItems=$('#cartItems'), total=$('#total'), bagCount=$('#bag span');
const session = localStorage.bodyGlueSession || (localStorage.bodyGlueSession=Math.random().toString(36).slice(2));
let shade='Clear', dragging=false, rx=-3, ry=-18, x0=0,y0=0;
function rotate(){bottle.style.transform=`translate(-50%,-50%) rotateX(${rx}deg) rotateY(${ry}deg)`}
stage.addEventListener('pointerdown',e=>{dragging=true;x0=e.clientX;y0=e.clientY;stage.setPointerCapture(e.pointerId)});
stage.addEventListener('pointermove',e=>{if(!dragging)return;ry+=(e.clientX-x0)*.32;rx-= (e.clientY-y0)*.18;rx=Math.max(-22,Math.min(15,rx));x0=e.clientX;y0=e.clientY;rotate()});
stage.addEventListener('pointerup',()=>dragging=false); stage.addEventListener('pointerleave',()=>dragging=false);
stage.addEventListener('pointermove',e=>{if(dragging)return;const r=stage.getBoundingClientRect();ry=-18+(e.clientX-r.left-r.width/2)/r.width*12;rx=-3-(e.clientY-r.top-r.height/2)/r.height*8;rotate()});
document.querySelectorAll('.swatch').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.swatch.active').classList.remove('active');b.classList.add('active');shade=b.dataset.shade;$('#shade').textContent=shade;bottle.style.setProperty('--bottle',b.dataset.color);document.dispatchEvent(new CustomEvent('bodyglue:shade',{detail:b.dataset.color}))}));
function openCart(){cart.classList.add('open');scrim.classList.add('open');cart.setAttribute('aria-hidden','false')}function closeCart(){cart.classList.remove('open');scrim.classList.remove('open');cart.setAttribute('aria-hidden','true')}
$('#bag').onclick=openCart;$('#closeCart').onclick=closeCart;scrim.onclick=closeCart;
function render(items){bagCount.textContent=items.length;total.textContent='$'+(items.length*34).toFixed(2);cartItems.innerHTML=items.length?items.map(i=>`<div class="cart-item"><div><b>${i.name}</b><small>${i.shade} · 50ml</small></div><b>$${i.price}.00</b></div>`).join(''):'<p class="empty">Your bag is ready when you are.</p>'}
async function getCart(){const r=await fetch('/api/cart',{headers:{'x-session':session}});render((await r.json()).items)}getCart().catch(()=>render([]));
$('#addCart').onclick=async()=>{try{const r=await fetch('/api/cart',{method:'POST',headers:{'Content-Type':'application/json','x-session':session},body:JSON.stringify({name:'Second Skin Adhesive',shade})});render((await r.json()).items)}catch{render([{name:'Second Skin Adhesive',shade,price:34}])}const t=$('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
document.querySelector('.checkout').onclick=()=>{alert('Demo checkout — your Body Glue bag is ready to connect to Stripe or Shopify.')};
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const canvas=$('#liquid'),ctx=canvas.getContext('2d');let dots=[];function size(){canvas.width=innerWidth;canvas.height=innerHeight;dots=Array.from({length:18},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:20+Math.random()*80,v:Math.random()*.22+.08}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);dots.forEach(d=>{d.y-=d.v;if(d.y+d.r<0)d.y=canvas.height+d.r;let g=ctx.createRadialGradient(d.x,d.y,0,d.x,d.y,d.r);g.addColorStop(0,'rgba(240,91,145,.12)');g.addColorStop(1,'rgba(240,91,145,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,7);ctx.fill()});requestAnimationFrame(draw)}size();draw();addEventListener('resize',size);
setTimeout(()=>{const p=$('#preloader');p.style.opacity=0;p.style.transition='opacity .45s';setTimeout(()=>p.remove(),500);document.querySelectorAll('.hero .reveal').forEach((e,i)=>setTimeout(()=>e.classList.add('in'),i*100))},1050);
